Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Виртуальная машина для ELK
  config.vm.define "elk" do |elk|
    elk.vm.network "private_network", type: "dhcp", ip: "192.168.56.10"
    elk.vm.network "forwarded_port", guest: 22, host: 2222  # Проброс порта для SSH
    elk.vm.network "forwarded_port", guest: 5601, host: 5601  # Проброс порта для Kibana
    elk.vm.network "forwarded_port", guest: 9200, host: 9200  # Проброс порта для Elasticsearch

    elk.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    # Провизионер для установки и настройки ELK Stack
    elk.vm.provision "ansible" do |ansible|
      ansible.playbook = "/Users/glucigir/college/proj/ansible/playbook.yml"
      ansible.inventory_path = "/Users/glucigir/college/proj/ansible/inventory.ini"
      ansible.become = true
    end
  end

  # Виртуальная машина для Vault
  config.vm.define "vault" do |vault|
    vault.vm.network "private_network", type: "dhcp", ip: "192.168.56.11"
    vault.vm.network "forwarded_port", guest: 22, host: 2200  # Проброс порта для SSH
    vault.vm.network "forwarded_port", guest: 8200, host: 8200  # Проброс порта для Vault

    vault.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    # Провизионер для установки Vault
    vault.vm.provision "ansible" do |ansible|
      ansible.playbook = "/Users/glucigir/college/proj/ansible/playbook.yml"
      ansible.inventory_path = "/Users/glucigir/college/proj/ansible/inventory.ini"
      ansible.become = true
    end
  end
end

