- name: Установка Vault
  apt:
    name: vault
    state: present
    update_cache: yes

- name: Копирование конфигурации Vault
  template:
    src: "vault.hcl.j2"
    dest: "/etc/vault/vault.hcl"
    mode: 0644

- name: Запуск и включение Vault
  systemd:
    name: vault
    enabled: yes
    state: started

